title: "Erikka Innes"
remote_theme: just-the-docs/just-the-docs


# Add this section to enable the remote theme plugin
plugins:
  - jekyll-remote-theme

# UI Settings
search_enabled: true
color_scheme: "dark"

aux_links:
  "GitHub": "https://github.com/erikkai"